remote: false

experienceLevel:
  internship: true
  entry: true
  associate: false
  mid-senior level: false
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: false
  part-time: false
  temporary: false
  internship: true
  other: false
  volunteer: false

date:
  all time: false
  month: true
  week: false
  24 hours: true

positions:
  - Software Engineer
  - Frontend Developer
  - Backend Developer
  - Full Stack Developer
  - Data Scientist
  - Software Developer internship
  - Software Engineer internship
  - Frontend Developer internship

locations:
  - USA

distance: 100

companyBlacklist:
  - Noir
  - Crossover

titleBlacklist:
